const DarkPremierImages =[
    {src:"https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:oi-discovery-catalog@@icons@@bms_premiere_v1.png,oit-false,ofo-bottom_left:q-80/et00372268-rrmnnxsvjw-portrait.jpg",
    alt:"Great Freedom",
    title:"Great Freedom",
    subtitle:"German",
    },
    {src:"https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:oi-discovery-catalog@@icons@@bms_premiere_v1.png,oit-false,ofo-bottom_left:q-80/et00373666-klpsdsnpct-portrait.jpg",
    alt:"Bancroft Series 2",
    title:"Bancroft Series 2",
    subtitle:"English",
    },
    {src:"https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:oi-discovery-catalog@@icons@@bms_premiere_v1.png,oit-false,ofo-bottom_left:q-80/et00357391-hulklpmwcd-portrait.jpg",
    alt:"Perfect Strangers",
    title:"Perfect Strangers",
    subtitle:"English",
    },
    {src:"https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:oi-discovery-catalog@@icons@@bms_premiere_v1.png,oit-false,ofo-bottom_left:q-80/et00373548-lthuffzfpu-portrait.jpg",
    alt:"Terror Twins: Talk To Me  & The Queen Mary",
    title:"Terror Twins: Talk To Me  & The Queen Mary",
    subtitle:"English",
    },
    {src:"https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:oi-discovery-catalog@@icons@@bms_premiere_v1.png,oit-false,ofo-bottom_left:q-80/et00072107-uawwuyrbhj-portrait.jpg",
    alt:"The Square",
    title:"The Square",
    subtitle:"English",
    },
    {src:"https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:oi-discovery-catalog@@icons@@bms_premiere_v1.png,oit-false,ofo-bottom_left:q-80/et00363042-aqxrqxtkne-portrait.jpg",
    alt:"Knights Of the Zodiac",
    title:"Knights of the Zodiac",
    subtitle:"English",
    },
    {src:"https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:oi-discovery-catalog@@icons@@bms_premiere_v1.png,oit-false,ofo-bottom_left:q-80/et00369688-lwmskgxvqs-portrait.jpg",
    alt:"The Chelsea Detective: Season 2",
    title:"The Chelsea Detective: Season 2",
    subtitle:"English",
    },
    {src:"https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:oi-discovery-catalog@@icons@@bms_premiere_v1.png,oit-false,ofo-bottom_left:q-80/et00374105-qyfbekdnly-portrait.jpg",
    alt:"Swan Princess, The: Far Longer Than Forever",
    title:"Swan Princess, The: Far Longer Than Forever",
    subtitle:"English",
    },
    ];
    export default DarkPremierImages;